
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/food_delivery
    username: root
    password: 112233
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/baeldung
          jwk-set-uri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/certs
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: akihoakana@gmail.com
    password: mmnxonechcwfyiwh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  servlet:
    context-path: /api
  port: 8081
#@ConfigurationProperties : Tự map key bên application thành đối tượng
#@Value(${tenkey}) : Lấy giá trị key bên appplication thành biến
file:
  upload-dir: /Users\dangt\Desktop\image
redis:
  host: localhost
  port: 6379

